### ISSUE TITLE
Erlang および Elixir のインストールにてエラーが発生します

### ISSUE THREAD

**Issue by bon2016** [HeRoMo/jupyter-langs#34]
イメージのビルド時に以下のエラーが発生します。

```
** (Mix) Could not compile dependency :lfe, "/root/.mix/rebar3 bare compile --paths /jupyter/ierl/_build/prod/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this depen
dency with "mix deps.compile lfe", update it with "mix deps.update lfe" or clean it with "mix deps.clean lfe"
```

調べたところ**Dockerfile**の163行目のコマンド`&& (cd apps/ierl && env MIX_ENV=prod mix escript.build) \`が原因のようです。

clone元の[filmor/ierl](https://github.com/filmor/ierl.git)のバージョンを全て試しましたが、解決しませんでした。

これは、C/C++を導入したくROOTを入れようとした際に発見しました。
そもそもROOTをの有無に関わらず同じエラーが発生しています。

**Comment by HeRoMo** [comment]
Elixir 1.13 がリリースされたためのようですね。
[filmor/ierl](https://github.com/filmor/ierl.git)がまだ1.13をサポートできていないようです。

ワークアラウンドですが次の箇所で `elixir=1.12.2-1` の様にバージョンを指定してやればエラーにならないと思います。
https://github.com/HeRoMo/jupyter-langs/blob/7703c22da4a57dd32fd2107dbf00a23e4c809726/Dockerfile#L154

**Comment by HeRoMo** [comment]
Release [5\.14\.0](https://github.com/HeRoMo/jupyter-langs/releases/tag/5.14.0) でワークアラウンドとしてElixirのバージョンを固定しました。
